-- MySQL Script generated by MySQL Workbench
-- Sun May  3 18:42:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_user_account_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`seller_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`seller_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`seller_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `shop_name` VARCHAR(150) NOT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_seller_profile_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_seller_profile_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(180) NOT NULL,
  `parent_category_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_category_slug` (`slug` ASC) VISIBLE,
  INDEX `fk_category_parent` (`parent_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_parent`
    FOREIGN KEY (`parent_category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `seller_profile_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(280) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_product_slug` (`slug` ASC) VISIBLE,
  INDEX `idx_product_seller_profile_id` (`seller_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_seller_profile`
    FOREIGN KEY (`seller_profile_id`)
    REFERENCES `mydb`.`seller_profile` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product_variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_variant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_variant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `variant_name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `currency_code` CHAR(3) NOT NULL DEFAULT 'USD',
  `status` VARCHAR(50) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_product_variant_sku` (`sku` ASC) VISIBLE,
  INDEX `idx_product_variant_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_variant_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`variant_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`variant_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`variant_image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_variant_id` BIGINT NOT NULL,
  `image_url` VARCHAR(500) NOT NULL,
  `alt_text` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_product_image_variant_id` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_variant`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `mydb`.`product_variant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_product_category_product_category` (`product_id` ASC, `category_id` ASC) VISIBLE,
  INDEX `idx_product_category_category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product_variant_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_variant_inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_variant_inventory` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_variant_id` BIGINT NOT NULL,
  `on_hand_quantity` INT NOT NULL DEFAULT 0,
  `reserved_quantity` INT NOT NULL DEFAULT 0,
  `reorder_threshold` INT NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_inventory_product_variant_id` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_variant`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `mydb`.`product_variant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `guest_token` VARCHAR(50) NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_cart_user_active` (`user_id` ASC, `status` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cart_id` BIGINT NOT NULL,
  `product_variant_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `added_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_cart_item_cart_variant` (`cart_id` ASC, `product_variant_id` ASC) VISIBLE,
  INDEX `idx_cart_item_variant_id` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_cart`
    FOREIGN KEY (`cart_id`)
    REFERENCES `mydb`.`cart` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cart_item_variant`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `mydb`.`product_variant` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`marketplace_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`marketplace_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`marketplace_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `cart_id` BIGINT NULL DEFAULT NULL,
  `order_number` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  `currency_code` CHAR(3) NOT NULL DEFAULT 'USD',
  `subtotal_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipping_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `tax_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipping_recipient_name` VARCHAR(200) NOT NULL,
  `shipping_line1` VARCHAR(255) NOT NULL,
  `shipping_line2` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_city` VARCHAR(120) NOT NULL,
  `shipping_state` VARCHAR(120) NULL DEFAULT NULL,
  `shipping_postal_code` VARCHAR(30) NOT NULL,
  `shipping_country_code` CHAR(2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_marketplace_order_number` (`order_number` ASC) VISIBLE,
  INDEX `idx_marketplace_order_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_marketplace_order_cart_id` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_marketplace_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_account` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_marketplace_order_cart`
    FOREIGN KEY (`cart_id`)
    REFERENCES `mydb`.`cart` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`seller_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`seller_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`seller_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `marketplace_order_id` BIGINT NOT NULL,
  `seller_profile_id` BIGINT NOT NULL,
  `seller_order_number` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  `subtotal_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipping_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `tax_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_seller_order_number` (`seller_order_number` ASC) VISIBLE,
  INDEX `idx_seller_order_marketplace_order_id` (`marketplace_order_id` ASC) VISIBLE,
  INDEX `idx_seller_order_seller_profile_id` (`seller_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_seller_order_marketplace_order`
    FOREIGN KEY (`marketplace_order_id`)
    REFERENCES `mydb`.`marketplace_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seller_order_seller_profile`
    FOREIGN KEY (`seller_profile_id`)
    REFERENCES `mydb`.`seller_profile` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `seller_order_id` BIGINT NOT NULL,
  `product_variant_id` BIGINT NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `unit_price_amount` DECIMAL(10,2) NOT NULL,
  `currency_code` CHAR(3) NOT NULL DEFAULT 'USD',
  `product_name_snapshot` VARCHAR(255) NOT NULL,
  `variant_name_snapshot` VARCHAR(255) NOT NULL,
  `image_url_snapshot` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_order_item_seller_order_id` (`seller_order_id` ASC) VISIBLE,
  INDEX `idx_order_item_product_variant_id` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_seller_order`
    FOREIGN KEY (`seller_order_id`)
    REFERENCES `mydb`.`seller_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_product_variant`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `mydb`.`product_variant` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`order_fulfillment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_fulfillment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_fulfillment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `seller_order_id` BIGINT NOT NULL,
  `fulfillment_status` VARCHAR(50) NOT NULL DEFAULT 'UNFULFILLED',
  `carrier` VARCHAR(100) NULL DEFAULT NULL,
  `tracking_number` VARCHAR(150) NULL DEFAULT NULL,
  `shipped_at` DATETIME NULL DEFAULT NULL,
  `delivered_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_order_fulfillment_seller_order_id` (`seller_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_fulfillment_seller_order`
    FOREIGN KEY (`seller_order_id`)
    REFERENCES `mydb`.`seller_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `marketplace_order_id` BIGINT NOT NULL,
  `provider` VARCHAR(100) NOT NULL,
  `provider_payment_reference` VARCHAR(150) NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  `amount` DECIMAL(10,2) NOT NULL,
  `currency_code` CHAR(3) NOT NULL DEFAULT 'USD',
  `paid_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_payment_provider_reference` (`provider_payment_reference` ASC) VISIBLE,
  INDEX `idx_payment_marketplace_order_id` (`marketplace_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_marketplace_order`
    FOREIGN KEY (`marketplace_order_id`)
    REFERENCES `mydb`.`marketplace_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `rating` INT NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_review_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_review_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_account` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL,
  `image_url` VARCHAR(500) NOT NULL,
  `alt_text` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_product_image_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
